# Auth Service

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../${custom.db.location}/${custom.db.name};IFEXISTS=TRUE
    username: sa
    password: auth_pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 5021

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${custom.eurekaPort}/eureka/

custom:
    eurekaPort: 5001
    db:
      location: db/auth-db/
      name: auth_db