/* VERSION Table*/
CREATE TABLE VERSION(
    VERSION VARCHAR(255)
);
INSERT INTO VERSION VALUES(
'1.0'
);

/* OAUTH_ACCESS_TOKEN Table*/
CREATE TABLE OAUTH_ACCESS_TOKEN (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID VARCHAR(50),
    CLIENT_SECRET VARCHAR(150),
    SCOPE VARCHAR(150),
    AUTHORIZED_GRANT_TYPES VARCHAR(150)
);
INSERT INTO OAUTH_ACCESS_TOKEN(
    CLIENT_ID,
    CLIENT_SECRET,
    SCOPE,
    AUTHORIZED_GRANT_TYPES
)
VALUES(
    'portal',
    '$2a$10$4bT4qTSIEVb/ZJ1A8PwTfu9T79WKhRaGfQR7QsLBhJVo.ZbGGTL8u',
    'read,write,trust',
    'authorization_code,password,refresh_token,implicit',
);